{{- if .Values.corootClusterAgent.enabled -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "corootClusterAgent.name" . }}
  labels:
    {{- include "corootClusterAgent.labels" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "corootClusterAgent.name" . }}-helm
subjects:
  - kind: ServiceAccount
    name: {{ include "corootClusterAgent.name" . }}
    namespace: {{ include "coroot.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "corootClusterAgent.name" . }}
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "corootClusterAgent.name" . }}
  labels:
    {{- include "corootClusterAgent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    {{- include "corootClusterAgent.selectorLabels" . | nindent 6 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "corootClusterAgent.name" . }}
  labels:
    {{- include "corootClusterAgent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "corootClusterAgent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ toYaml .Values.corootClusterAgent.config | sha256sum }}
        {{- with .Values.corootClusterAgent.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "corootClusterAgent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.corootClusterAgent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "corootClusterAgent.name" . }}
      securityContext:
        {{- toYaml .Values.corootClusterAgent.podSecurityContext | nindent 8 }}
      containers:
        - name: cluster-agent
          securityContext:
            {{- toYaml .Values.corootClusterAgent.securityContext | nindent 12 }}
          image: "{{ .Values.corootClusterAgent.image.repository }}:{{ .Values.corootClusterAgent.image.tag }}"
          imagePullPolicy: {{ .Values.corootClusterAgent.image.pullPolicy }}
          env:
            - name: LISTEN
              value: "{{ .Values.corootClusterAgent.config.listen }}"
            - name: COROOT_URL
              value: "{{ .Values.corootClusterAgent.config.coroot_url }}"
            - name: API_KEY
              value: "{{ .Values.corootClusterAgent.config.api_key }}"
            - name: CONFIG_UPDATE_INTERVAL
              value: "{{ .Values.corootClusterAgent.config.config.update.interval }}"
            - name: CONFIG_UPDATE_TIMEOUT
              value: "{{ .Values.corootClusterAgent.config.config.update.timeout }}"
            - name: METRICS_SCRAPE_INTERVAL
              value: "{{ .Values.corootClusterAgent.config.metrics.scrape.interval }}"
            - name: METRICS_SCRAPE_TIMEOUT
              value: "{{ .Values.corootClusterAgent.config.metrics.scrape.timeout }}"
            - name: METRICS_WAL_DIR
              value: "{{ .Values.corootClusterAgent.config.metrics.wal_dir }}"
            - name: PROFILES_SCRAPE_INTERVAL
              value: "{{ .Values.corootClusterAgent.config.profiles.scrape.interval }}"
            - name: PROFILES_SCRAPE_TIMEOUT
              value: "{{ .Values.corootClusterAgent.config.profiles.scrape.timeout }}"
          {{- with .Values.corootClusterAgent.env }}
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.corootClusterAgent.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
              readOnly: false
      volumes:
        - emptyDir: {}
          name: tmp
      {{- with .Values.corootClusterAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.corootClusterAgent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.corootClusterAgent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "corootClusterAgent.name" . }}
  labels:
    {{- include "corootClusterAgent.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - persistentvolumes
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
      - volumeattachments
    verbs:
      - get
      - list
      - watch

{{- end -}}
