apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    name: cart
spec:
  replicas: 2
  selector:
    matchLabels:
      name: cart
  template:
    metadata:
      annotations:
        coroot.com/profile-scrape: "true"
        coroot.com/profile-port: "80"
      labels:
        name: cart
    spec:
      containers:
        - name: cart
          image: failurepedia/cart:0.9
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 80
          env:
            - name: LISTEN
              value: "0.0.0.0:80"
            - name: DBADDR
              value: "odb-redis-master:6379"
            - name: OPENTELEMETRY_COLLECTOR_ENDPOINT
              value: {{ .Values.otel.endpoint }}
            - name: OTEL_SDK_DISABLED
              value: "{{ .Values.otel.disabled }}"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    name: cart
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: cart
