apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-db-init
spec:
  template:
    metadata:
      labels: {app: catalog-db-init}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: app
          image: failurepedia/catalog:0.41
          command:
            - "/catalog"
            - "--fill=1000000"
          env:
            - name: PGDATABASE
              value: demo
            - name: PGUSER
              value: demo
            - name: PGPASSWORD
              valueFrom: { secretKeyRef: { name: demo.odb-postgres.credentials.postgresql.acid.zalan.do, key: password } }
            - name: PGHOST
              value: odb-postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    name: catalog
spec:
  replicas: 3
  selector:
    matchLabels:
      name: catalog
  template:
    metadata:
      annotations:
        coroot.com/profile-scrape: "true"
        coroot.com/profile-port: "80"
      labels:
        name: catalog
    spec:
      containers:
        - name: catalog
          image: failurepedia/catalog:0.44
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 80
          env:
            - name: LISTEN
              value: "0.0.0.0:80"
            - name: PGDATABASE
              value: demo
            - name: PGUSER
              value: demo
            - name: PGPASSWORD
              valueFrom: { secretKeyRef: { name: demo.odb-postgres.credentials.postgresql.acid.zalan.do, key: password } }
            - name: PGHOST
              value: odb-postgres
            - name: OPENTELEMETRY_COLLECTOR_ENDPOINT
              value: {{ .Values.otel.endpoint }}
            - name: OTEL_SDK_DISABLED
              value: "{{ .Values.otel.disabled }}"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 1

---

apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    name: catalog
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: catalog
