apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      annotations:
        coroot.com/profile-scrape: "true"
        coroot.com/profile-port: "80"
      labels:
        name: frontend
    spec:
      containers:
        - name: frontend
          image: failurepedia/front-end:0.30
          resources:
            limits:
              cpu: 700m
              memory: 200Mi
            requests:
              cpu: 700m
              memory: 100Mi
          ports:
            - containerPort: 80
          env:
            - name: LISTEN
              value: "0.0.0.0:80"
            - name: SESSION_DB
              value: "odb-memcached:11211"
            - name: OPENTELEMETRY_COLLECTOR_ENDPOINT
              value: {{ .Values.otel.endpoint }}
            - name: OTEL_SDK_DISABLED
              value: "{{ .Values.otel.disabled }}"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: frontend
