apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-test

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: load-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: load-test
    namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  labels:
    name: load-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: load-test
  template:
    metadata:
      annotations:
        coroot.com/profile-scrape: "true"
        coroot.com/profile-port: "8080"
      labels:
        name: load-test
    spec:
      serviceAccountName: load-test
      containers:
        - name: user
          image: failurepedia/load-test:0.30
          command:
            - "/load-test"
            - "--timeout=2000ms"
            - "--concurrency=70"
            - "--sleep=1000ms"
            - "--listen=:8080"
            - "--url=http://frontend"
          resources:
            limits:
              cpu: 700m
              memory: 200Mi
            requests:
              cpu: 700m
              memory: 200Mi
          ports:
            - containerPort: 8080
