{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-mysql-secret" .Release.Name) -}}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
  labels:
    app: {{ .Release.Name }}-mysql
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"  # Runs before MySQL deployment
type: Opaque
data:
  mysql-root-password: {{ randAlphaNum 16 | b64enc | quote }}
  mysql-password: {{ randAlphaNum 16 | b64enc | quote }}
  mysql-replication-password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
