apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    name: order
spec:
  replicas: 2
  selector:
    matchLabels:
      name: order
  template:
    metadata:
      annotations:
        coroot.com/profile-scrape: "true"
        coroot.com/profile-port: "80"
      labels:
        name: order
    spec:
      containers:
        - name: order
          image: failurepedia/order:0.15
          resources:
            requests:
              memory: 200Mi
          ports:
            - containerPort: 80
          env:
            - name: LISTEN
              value: "0.0.0.0:80"
            - name: MONGO_HOST
              value: odb-mongodb-headless
            - name: OPENTELEMETRY_COLLECTOR_ENDPOINT
              value: {{ .Values.otel.endpoint }}
            - name: OTEL_SDK_DISABLED
              value: "{{ .Values.otel.disabled }}"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 1

---

apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    name: order
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: order
